### ISSUE TITLE
can't build with CCE + ROCm

### ISSUE THREAD

**Issue by BenWibking** [quokka-astro/quokka#309]
ROCm 5.0 can't build the latest AMReX due to a compiler bug. Since this is the version provided on Setonix, this means we can't currently build Quokka on Setonix.

Per Weiqun, we need to ask Setonix staff to install ROCm 5.2.

**Comment by markkrumholz** [comment]
Do you want to contact Pawsey staff, or would you like me to? If you would like me to, could you please just post / send me a snippet of the error message.

**Comment by BenWibking** [comment]
> Do you want to contact Pawsey staff, or would you like me to? If you would like me to, could you please just post / send me a snippet of the error message.

I would prefer if you would. The error message is:
```
error: Linking globals named '_ZN5amrex18ParallelDescriptor11ioProcessorE': symbol multiply defined!
clang-14: error: linker command failed with exit code 1 (use -v to see invocation)
```

According to Weiqun: "There are several extern variables in ParallelDescriptor. But ioProcessor is the only extern const (which is perfectly legal!)." AMReX builds and runs successfully with ROCm 5.2 on Frontier.

**Comment by BenWibking** [comment]
Also- ROCm 5.3 and 5.4 have performance regressions (seen in other AMReX codes on Frontier) and ROCm 5.5 is not yet supported on Frontier, so we couldn't get support from the AMReX team if we were to encounter problems with it.

Edit: ROCm 5.5 apparently still has the performance regression. All versions 5.3-5.5 cause a 2x slowdown in WarpX (!)

**Comment by markkrumholz** [comment]
OK, I have put in the request. Will let you know when I hear back, but it's a holiday in Australia today, so probably tomorrow at the earliest.

**Comment by BenWibking** [comment]
I've tried building on Frontier with rocm/5.2 and it still doesn't work. Something very odd is happening here. Since all the CI builds pass and it builds successfully on all non-Cray machines I've tried, I suspect the issue is with the Cray compilers.

**Comment by BenWibking** [comment]
Interestingly, WarpX now recommends avoiding the Cray compilers on Frontier: https://github.com/ECP-WarpX/WarpX/pull/3986

**Comment by BenWibking** [comment]
I've tried the WarpX-recommended settings on Frontier, using:
```
export CC=$(which hipcc)
export CXX=$(which hipcc)
export LDFLAGS="-L${ROCM_PATH}/lib -lamdhip64 ${PE_MPICH_GTL_DIR_amd_gfx90a} -lmpi_gtl_hsa"
```
to avoid the Cray compilers entirely (I hope).

But then I get:
```
In file included from /ccs/home/wibking/quokka/src/hyperbolic_system.hpp:35:
/ccs/home/wibking/quokka/src/simulation.hpp:16:10: fatal error: 'filesystem' file not found
#include <filesystem>
         ^~~~~~~~~~~~
1 error generated when compiling for gfx90a.
```

**Comment by BenWibking** [comment]
This might be related to: https://github.com/AMReX-Codes/amrex/pull/3355.

Edit: applying this patch did not fix the issue.

**Comment by BenWibking** [comment]
Ok, it still doesn't work with hipcc + ROCm 5.4.3:
```
[100%] Linking CXX executable test_hydro_shocktube
clang-15: warning: argument unused during compilation: '-Xoffload-linker --whole-archive' [-Wunused-command-line-argument]
lld: error: duplicate symbol: amrex::RealVect::Zero
>>> defined in /tmp/AMReX_RealVect-a51173/AMReX_RealVect-gfx90a.o
>>> defined in /tmp/AMReX_RealVect-4ea64f/AMReX_RealVect-gfx90a.o

lld: error: duplicate symbol: amrex::RealVect::Unit
>>> defined in /tmp/AMReX_RealVect-a51173/AMReX_RealVect-gfx90a.o
>>> defined in /tmp/AMReX_RealVect-4ea64f/AMReX_RealVect-gfx90a.o

lld: error: duplicate symbol: amrex::IntVect::Zero
>>> defined in /tmp/AMReX_IntVect-6460c7/AMReX_IntVect-gfx90a.o
>>> defined in /tmp/AMReX_IntVect-67e54e/AMReX_IntVect-gfx90a.o

lld: error: duplicate symbol: amrex::IntVect::Unit
>>> defined in /tmp/AMReX_IntVect-6460c7/AMReX_IntVect-gfx90a.o
>>> defined in /tmp/AMReX_IntVect-67e54e/AMReX_IntVect-gfx90a.o

lld: error: duplicate symbol: amrex::FPC::normal_float_order
>>> defined in /tmp/AMReX_FPC-d4d019/AMReX_FPC-gfx90a.o
>>> defined in /tmp/AMReX_FPC-30f5db/AMReX_FPC-gfx90a.o

lld: error: duplicate symbol: amrex::FPC::reverse_float_order
>>> defined in /tmp/AMReX_FPC-d4d019/AMReX_FPC-gfx90a.o
>>> defined in /tmp/AMReX_FPC-30f5db/AMReX_FPC-gfx90a.o

lld: error: duplicate symbol: amrex::FPC::reverse_float_order_2
>>> defined in /tmp/AMReX_FPC-d4d019/AMReX_FPC-gfx90a.o
>>> defined in /tmp/AMReX_FPC-30f5db/AMReX_FPC-gfx90a.o

lld: error: duplicate symbol: amrex::FPC::normal_double_order
>>> defined in /tmp/AMReX_FPC-d4d019/AMReX_FPC-gfx90a.o
>>> defined in /tmp/AMReX_FPC-30f5db/AMReX_FPC-gfx90a.o

lld: error: duplicate symbol: amrex::FPC::reverse_double_order
>>> defined in /tmp/AMReX_FPC-d4d019/AMReX_FPC-gfx90a.o
>>> defined in /tmp/AMReX_FPC-30f5db/AMReX_FPC-gfx90a.o

lld: error: duplicate symbol: amrex::FPC::reverse_double_order_2
>>> defined in /tmp/AMReX_FPC-d4d019/AMReX_FPC-gfx90a.o
>>> defined in /tmp/AMReX_FPC-30f5db/AMReX_FPC-gfx90a.o

lld: error: duplicate symbol: amrex::FPC::ieee_float
>>> defined in /tmp/AMReX_FPC-d4d019/AMReX_FPC-gfx90a.o
>>> defined in /tmp/AMReX_FPC-30f5db/AMReX_FPC-gfx90a.o

lld: error: duplicate symbol: amrex::FPC::ieee_double
>>> defined in /tmp/AMReX_FPC-d4d019/AMReX_FPC-gfx90a.o
>>> defined in /tmp/AMReX_FPC-30f5db/AMReX_FPC-gfx90a.o

lld: error: duplicate symbol: amrex::Arena::align_size
>>> defined in /tmp/AMReX_Arena-8cacb7/AMReX_Arena-gfx90a.o
>>> defined in /tmp/AMReX_Arena-134bf1/AMReX_Arena-gfx90a.o

lld: error: duplicate symbol: amrex::ParallelDescriptor::ioProcessor
>>> defined in /tmp/AMReX_ParallelDescriptor-98f559/AMReX_ParallelDescriptor-gfx90a.o
>>> defined in /tmp/AMReX_ParallelDescriptor-9aed16/AMReX_ParallelDescriptor-gfx90a.o
clang-15: error: amdgcn-link command failed with exit code 1 (use -v to see invocation)
```

It does build with the HIP CI, which uses ROCm 5.5.1...

**Comment by BenWibking** [comment]
I think this is related to the object library `QuokkaObj` that was recently introduced to the build process.

**Comment by BenWibking** [comment]
Somehow we are linking AMReX twice:
```
[100%] Linking CXX executable test_hydro_shocktube
cd /ccs/home/wibking/quokka/build/src/HydroShocktube && /autofs/nccs-svm1_sw/frontier/spack-envs/base/opt/linux-sles15-x86_64/gcc-7.5.0/cmake-3.23.2-4r4mpiba7cwdw2hlakh5i7tchi64s3qd/bin/cmake -E cmake_link_script CMakeFiles/test_hydro_shocktube.dir/link.txt --verbose=1
/opt/rocm-5.4.3/bin/hipcc -I/opt/rocm-5.4.3/include -O3 -DNDEBUG -L/opt/rocm-5.4.3/lib -lamdhip64 -L/opt/cray/pe/mpich/8.1.23/gtl/lib -lmpi_gtl_hsa -Xoffload-linker --whole-archive -fgpu-rdc CMakeFiles/test_hydro_shocktube.dir/test_hydro_shocktube.cpp.o CMakeFiles/test_hydro_shocktube.dir/__/fextract.cpp.o CMakeFiles/test_hydro_shocktube.dir/__/interpolate.cpp.o ../CMakeFiles/QuokkaObj.dir/main.cpp.o ../CMakeFiles/QuokkaObj.dir/CloudyCooling.cpp.o ../CMakeFiles/QuokkaObj.dir/GrackleDataReader.cpp.o -o test_hydro_shocktube  -Wl,-rpath,/sw/frontier/spack-envs/base/opt/cray-sles15-zen3/cce-15.0.0/hdf5-1.14.0-uzik26xpydtjsv32ju4nk7tkxa6dos5n/lib:/opt/cray/pe/mpich/8.1.23/ofi/cray/10.0/lib:/opt/rocm-5.4.3/hip/lib -lstdc++fs ../../amrex/Src/libamrex_1d.a ../../fmt/libfmt.a /sw/frontier/spack-envs/base/opt/cray-sles15-zen3/cce-15.0.0/hdf5-1.14.0-uzik26xpydtjsv32ju4nk7tkxa6dos5n/lib/libhdf5.so.310.0.0 -lstdc++fs ../../amrex/Src/libamrex_1d.a /opt/cray/pe/mpich/8.1.23/ofi/cray/10.0/lib/libmpi_cray.so /opt/rocm-5.4.3/lib/libhiprand.so.1.1.50403 /opt/rocm-5.4.3/lib/librocrand.so.1.1.50403 /opt/rocm-5.4.3/hip/lib/libamdhip64.so.5.4.50403 /opt/rocm-5.4.3/llvm/lib/clang/15.0.0/lib/linux/libclang_rt.builtins-x86_64.a --hip-link --offload-arch=gfx90a ../../fmt/libfmt.a /sw/frontier/spack-envs/base/opt/cray-sles15-zen3/cce-15.0.0/hdf5-1.14.0-uzik26xpydtjsv32ju4nk7tkxa6dos5n/lib/libhdf5.so.310.0.0
```

**Comment by BenWibking** [comment]
@psharda  This is caused by the object library:
```
#create an object library for files that should be compiled with all test problems
set (QuokkaObjSources "${CMAKE_CURRENT_SOURCE_DIR}/main.cpp" "${CMAKE_CURRENT_SOURCE_DIR}/CloudyCooling.cpp" "${CMAKE_CURRENT_SOURCE_DIR}/GrackleDataReader.cpp")
add_library(QuokkaObj OBJECT ${QuokkaObjSources})

if(AMReX_GPU_BACKEND MATCHES "CUDA")
    setup_target_for_cuda_compilation(QuokkaObj)
endif()

link_libraries(QuokkaObj)
```

Since before creating the object library, we called `link_libraries` for stdc++fs and AMReX, those get added twice in the final linker command.

**Comment by BenWibking** [comment]
Working on a workaround...

**Comment by BenWibking** [comment]
This appears to be the issue: https://gitlab.kitware.com/cmake/cmake/-/issues/18090

**Comment by psharda** [comment]
Hopefully #316 will fix this issue too.

**Comment by BenWibking** [comment]
Fixed by https://github.com/quokka-astro/quokka/pull/311.
